export const ACCESS_TOKEN_COOKIE_PATH = "/api";
export const REFRESH_TOKEN_COOKIE_PATH = "/api/auth";

export const ACCESS_TOKEN_COOKIE_NAME = "accessToken";
export const REFRESH_TOKEN_COOKIE_NAME = "refreshToken";

export const STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const MILLISECONDS_IN_A_SECOND = 1000;
export const SECONDS_IN_A_MINUTE = 60;
export const MILLISECONDS_IN_A_MINUTE = 60 * MILLISECONDS_IN_A_SECOND;
export const SECONDS_IN_AN_HOUR = SECONDS_IN_A_MINUTE * 60;
export const SECONDS_IN_A_DAY = SECONDS_IN_AN_HOUR * 24;

export const EMAIL_VERIFICATION_TOKEN_EXPIRY_MINUTES = 10;
export const PASSWORD_RESET_TOKEN_EXPIRY_MINUTES = 10;
